version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_newsletter
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DBNAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - backend_network
    ports:
      - "3307:3306"

  newsletter:
    build: .
    ports:
      - 8004:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - mysql
    networks:
      - backend_network

  worker:
    build: .
    command: celery -A app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - newsletter
      - redis
      - mysql
    networks:
      - backend_network

  celery_beat:
    build: .
    command: celery -A app beat --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - mysql
    networks:
      - backend_network

  redis:
    image: redis:latest
    container_name: redis_newsletter
    networks:
      - backend_network
    ports:
      - "6379:6379"

networks:
  backend_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
