version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DBNAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - backend_network
    ports:
      - "3306:3306"
    command:
      [
        "bash",
        "-c",
        "chmod -R 644 /docker-entrypoint-initdb.d/* && /usr/local/bin/docker-entrypoint.sh mysqld",
      ]

  newsletter:
    build: .
    restart: unless-stopped
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - mysql
    networks:
      - backend_network

  worker:
    build: .
    restart: unless-stopped
    command: celery -A app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - newsletter
      - redis
      - mysql
    networks:
      - backend_network

  celery_beat:
    build: .
    restart: unless-stopped
    command: celery -A app beat --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - mysql
    networks:
      - backend_network

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis_newsletter
    networks:
      - backend_network
    ports:
      - "6379:6379"

networks:
  backend_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
